services:
  web:
    build:
      context: .               # This is your root folder with Dockerfile
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/app                # Mount current folder into container
    restart: unless-stopped
